from google.adk.agents import Agent
from google.adk.models import Gemini
from google.adk.runners import Runner
from google.adk.sessions.in_memory_session_service import InMemorySessionService
from google.genai import types
import logging
import traceback
import sys
import os

# Configure logging to stdout so it shows up in Cloud Run
logging.basicConfig(level=logging.INFO, stream=sys.stdout)
logger = logging.getLogger(__name__)

_runner = None

def get_runner():
    global _runner
    if _runner is None:
        try:
            logger.info("Initializing Agent and Runner...")
            
            # Use Vertex AI backend on Google Cloud Platform
            # Force the underlying library to use Vertex AI instead of Public Gemini API
            os.environ["GOOGLE_GENAI_USE_VERTEXAI"] = "true"
            
            project_id = os.environ.get("GOOGLE_CLOUD_PROJECT")
            location = os.environ.get("GOOGLE_CLOUD_LOCATION", "us-central1")
            logger.info(f"Using Project ID: {project_id}, Location: {location}")

            # Updated to use Gemini 2.5 Flash as confirmed by your project's Model Garden
            model = Gemini(model="gemini-2.5-flash")
            logger.info(f"Gemini model object created. Backend: {model._api_backend}, Model: {model.model}")
            
            # Initialize the Feedback Agent
            feedback_agent = Agent(
                name="FeedbackIntelligenceAgent",
                model=model,
                instruction="""
                You are a specialized Customer Feedback Intelligence AI.
                Analyze reviews and provide: 1. SENTIMENT (Positive/Neutral/Negative), 
                2. SUMMARY (2 sentences max), 3. SUGGESTED RESPONSE.
                Output your analysis in a clear, professional format.
                """
            )
            
            # Initialize Runner with InMemorySessionService
            # auto_create_session ensures we don't hit SessionNotFoundError
            _runner = Runner(
                app_name="CustomerFeedbackApp",
                agent=feedback_agent,
                session_service=InMemorySessionService(),
                auto_create_session=True
            )
            logger.info("Runner initialized successfully.")
        except Exception as e:
            logger.error(f"Failed to initialize agent/runner: {str(e)}")
            logger.error(traceback.format_exc())
            raise e
    return _runner

async def analyze_feedback(text: str):
    logger.info(f"Starting analysis for text: {text[:50]}...")
    runner = get_runner()
    
    # Create the user message content
    new_message = types.Content(
        role="user",
        parts=[types.Part.from_text(text=text)]
    )
    
    session_id = "session_1" 
    user_id = "user_1"
    
    try:
        final_text = ""
        logger.info("Invoking runner.run_async...")
        async for event in runner.run_async(
            user_id=user_id,
            session_id=session_id,
            new_message=new_message
        ):
            # Log author for clarity
            if hasattr(event, 'author') and event.author:
                logger.info(f"Agent event received from: {event.author}")

            # Correctly extract text from event.content.parts
            if hasattr(event, 'content') and event.content and event.content.parts:
                for part in event.content.parts:
                    if hasattr(part, 'text') and part.text:
                        final_text += part.text
        
        if not final_text:
            logger.warning("No text extracted from agent events.")
            return "Error: No response generated by the agent. Please check logs for connection details."
            
        logger.info("Analysis complete.")
        return final_text
        
    except Exception as e:
        logger.error(f"Error during agent execution: {str(e)}")
        logger.error(traceback.format_exc())
        raise e

if __name__ == "__main__":
    import asyncio
    sample_review = "The product is great, but the delivery was delayed by 3 days."
    print("Testing locally...")
    try:
        print(asyncio.run(analyze_feedback(sample_review)))
    except Exception:
        pass

